      - name: Debug parsed outputs
        run: |
          echo "CONFIG='${{ steps.parse.outputs.config }}'"
          echo "JOBID='${{ steps.parse.outputs.jobId }}'"
          echo "USERID='${{ steps.parse.outputs.userId }}'"